[package]
name = "super2"
version = "0.1"
lean_version = "3.5c"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "89fd08834bca00a7bd47b57c3cd8e78bba6216c9"}
